[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
vuln_missing_signer = "45oLukKiFBS7RD9nY414inaKV9bypSxy4RYVEE1rgZkU"
vuln_arithmetic_overflow = "54jifQzQUTxctTvfpSDUfaqG37NqACEMkaePgCyjKkyv"
vuln_pda_seed_leak = "7rgXjj24ujXjAa4sZp6R2RmZCSHYGFAmAJ5S8RgapNwY"
vuln_account_closing = "89m1e57mfnsPvqdKpYpSfRsDSXDWjg3Cky7MYb9P2dF6"
vuln_type_confusion = "6byh1jEaakt1ew4bEpGUa8Hr9wQ6nvXMB7f5jxqJgWmb"
vuln_zero_copy_alignment = "AbQinz5UQX1utqkHT55FmTZ123nfqA48HRZfE1m9hmHU"
vuln_hook_reentrancy = "CjoyCukZW7eLwNqYrNk5Sn2144hBer5mpFjusVVMEXVp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"