[workspace]
members = [
    "programs/*",
    "benchmarks",
]
resolver = "2"

[workspace.dependencies]
subtle = "2.6.1"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
panic = "abort"
