[workspace]
members = [
    "programs/*",
]
resolver = "2"

[workspace.dependencies]
subtle = "2.6.1"

[patch.crates-io]
blake3 = { git = "https://github.com/BLAKE3-team/BLAKE3.git", tag = "1.5.0" }

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
panic = "abort"
