[package]
name = "vuln_hook_reentrancy"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = "0.30.1"
solana-program = "1.18.26"
solana-security-txt = "1.1.1"
anchor-spl = "0.30.1"