[package]
name = "vuln_type_confusion"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = "0.30.1"
solana-program = "1.18"
solana-security-txt = "1.1.1"
